//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiplePasswordsEncrypter.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MultiplePasswordsEncrypter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Add Folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BtnAddDir {
            get {
                return ResourceManager.GetString("BtnAddDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BtnAddFile {
            get {
                return ResourceManager.GetString("BtnAddFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Question に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BtnAddQuestion {
            get {
                return ResourceManager.GetString("BtnAddQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Decrypt に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BtnDecrypt {
            get {
                return ResourceManager.GetString("BtnDecrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Encrypt に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BtnEncrypt {
            get {
                return ResourceManager.GetString("BtnEncrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BtnRemove {
            get {
                return ResourceManager.GetString("BtnRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BtnSelect {
            get {
                return ResourceManager.GetString("BtnSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BtnSelectFile {
            get {
                return ResourceManager.GetString("BtnSelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create a folder and expand. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChkCreateDir {
            get {
                return ResourceManager.GetString("ChkCreateDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Expand to desktop. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChkDecompressDesktop {
            get {
                return ResourceManager.GetString("ChkDecompressDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ignore case. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChkIgnoreCase {
            get {
                return ResourceManager.GetString("ChkIgnoreCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (ja)Ignore Hiragana and Katakana. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChkIgnoreHiraKata {
            get {
                return ResourceManager.GetString("ChkIgnoreHiraKata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (ja)Ignore Zenkaku and Hankaku. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChkIgnoreZenHan {
            get {
                return ResourceManager.GetString("ChkIgnoreZenHan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   To create an archive without compression. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChkNoCompress {
            get {
                return ResourceManager.GetString("ChkNoCompress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ignore whitespace in password. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChkRemoveSpace {
            get {
                return ResourceManager.GetString("ChkRemoveSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove whitespace before and after password. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChkTrim {
            get {
                return ResourceManager.GetString("ChkTrim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   or more passwords are required for decryption. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CmbNumRequiredPasswords {
            get {
                return ResourceManager.GetString("CmbNumRequiredPasswords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output Dir: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LblOutputDir {
            get {
                return ResourceManager.GetString("LblOutputDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output File: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LblOutputFile {
            get {
                return ResourceManager.GetString("LblOutputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target File: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LblTargetFile {
            get {
                return ResourceManager.GetString("LblTargetFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete question {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgCDeleteQuestion {
            get {
                return ResourceManager.GetString("MsgCDeleteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Encrypt with existing files only? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgCEncryptOnlyExistFile {
            get {
                return ResourceManager.GetString("MsgCEncryptOnlyExistFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The output file exists. Do you want to overwrite? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgCOverwriteOutputFile {
            get {
                return ResourceManager.GetString("MsgCOverwriteOutputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start encryption. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgCStartEncryption {
            get {
                return ResourceManager.GetString("MsgCStartEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to create the output file.\n\nDetailed information: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgEFailCreateFile {
            get {
                return ResourceManager.GetString("MsgEFailCreateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Encryption failed.\n\nDetailed information: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgEFailEncryption {
            get {
                return ResourceManager.GetString("MsgEFailEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output file is not specified. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgEOutputNotSpecified {
            get {
                return ResourceManager.GetString("MsgEOutputNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Only one Question can not be deleted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgERemoveLastQuestion {
            get {
                return ResourceManager.GetString("MsgERemoveLastQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Encryption is impossible due to duplicate file name or folder name. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgETargetDuplicated {
            get {
                return ResourceManager.GetString("MsgETargetDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no file to encrypt. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgETargetNotExisted {
            get {
                return ResourceManager.GetString("MsgETargetNotExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The specified file is not a Multiple Passwords Encrypted file.\n\nDetailed information: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgETargetNotMPE {
            get {
                return ResourceManager.GetString("MsgETargetNotMPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Encryption target file is not specified. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgETargetNotSpecified {
            get {
                return ResourceManager.GetString("MsgETargetNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Decryption is complete. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgIEndDecryption {
            get {
                return ResourceManager.GetString("MsgIEndDecryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Encryption is complete. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgIEndEncryption {
            get {
                return ResourceManager.GetString("MsgIEndEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password is incorrect. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgIPasswordIncorrect {
            get {
                return ResourceManager.GetString("MsgIPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Excludes the selected file or folder from subject to encryption. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgIRemoveNoTargetItem {
            get {
                return ResourceManager.GetString("MsgIRemoveNoTargetItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A Question without a password is a dummy Question. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgWDummyQuestion {
            get {
                return ResourceManager.GetString("MsgWDummyQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The following file does not exist. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgWFileNotExisted {
            get {
                return ResourceManager.GetString("MsgWFileNotExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The specified file may not be decrypted properly.\n\nDetailed information: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgWMPEInvalidFormat {
            get {
                return ResourceManager.GetString("MsgWMPEInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Because it is less than the number of passwords required for decryption, an archive that can not be decrypted is created. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MsgWUndecrytableArchive {
            get {
                return ResourceManager.GetString("MsgWUndecrytableArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Decrypt に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TabDecrypt {
            get {
                return ResourceManager.GetString("TabDecrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Encrypt に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TabEncrypt {
            get {
                return ResourceManager.GetString("TabEncrypt", resourceCulture);
            }
        }
    }
}
